###all customers
GET http://localhost:8082/customers/all

###add customer
GET http://localhost:8082/customers/add1/vasya

###add customer 2
GET http://localhost:8082/customers/add2/valya

###update customer email
GET http://localhost:8082/customers/update/gmail

###update again
GET http://localhost:8082/customers/update/updated

###add new address
POST http://localhost:8082/address/add/prague-u%20zatisi%201-14700
Content-Type: application/x-www-form-urlencoded

###update address
GET http://localhost:8082/address/update

###all addresses
GET http://localhost:8082/address/all

###prague addresses
GET http://localhost:8082/address/all/prague

###person names
GET http://localhost:8082/getPersonNames

###persons: test SPEL
GET http://localhost:8082/testEntityNameSpEL

###update person
GET http://localhost:8082/updatePerson/3

###team: test SPEL
GET http://localhost:8082/team/customeQueryWithSpEL

###team by title
GET http://localhost:8082/team/findByTitle

###team native query
GET http://localhost:8082/team/nativeQueryTest



