insert into foo.person(firstname, lastname) VALUES ( 'maria','stepanova' );
insert into foo.person(firstname, lastname) VALUES ( 'daria','glupova' );
insert into foo.person(firstname, lastname) VALUES ( 'ivan','mashkin' );
insert into foo.person(firstname, lastname) VALUES ( 'vasiliy','pupkin' );
insert into foo.person(firstname, lastname) VALUES ( 'petr','ivanov' );
insert into foo.team(description, title, size) VALUES ('first team', 'team1', 10);
insert into foo.team(description, title, size) VALUES ('second team', 'team2', 8);
insert into foo.team(description, title, size) VALUES ('third team', 'team3', 7);
insert into foo.address(city, street, zipcode) VALUES ( 'prague', 'holeckova 26', '15000' );
insert into foo.address(city, street, zipcode) VALUES ( 'london', '5 holly rd ', 'TW14EA' );