drop table if exists person;
drop table if exists team;
drop table if exists address;
create table if not exists person (
                                      id INT NOT NULL generated BY DEFAULT AS IDENTITY ,
                                      firstname VARCHAR(50),
                                      lastname VARCHAR(50)
);
create table if not exists team (
                                          id INT NOT NULL generated BY DEFAULT AS IDENTITY ,
                                          description VARCHAR(50),
                                          title VARCHAR(50),
                                           size INT
);
create table if not exists address(
                                          id INT NOT NULL generated BY DEFAULT AS IDENTITY ,
                                          city VARCHAR(50),
                                          street VARCHAR(50),
                                          zipcode VARCHAR(10)
);
